# Generated by Django 5.0.14 on 2026-05-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_representationreservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmee'), ('canceled', 'Annulee')], default='confirmed', max_length=60),
        ),
    ]
