# Generated by Django 5.0.14 on 2026-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_provider',
            field=models.CharField(blank=True, default='stripe', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non paye'), ('paid', 'Paye'), ('failed', 'Echoue')], default='unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('confirmed', 'Confirmee'), ('canceled', 'Annulee')], default='confirmed', max_length=60),
        ),
    ]
